In [1]:
import cv2


In [2]:
input=cv2.imread(r"C:\\Users\\prasa\\OneDrive\\Desktop\\photo.JPG",-1) # to read/ load an image   
# 0 indicates gray scale image
#1 indicates colour image
#-1 indiactes colour image with alpha channel
print(input)


[[[174 166 153]
  [174 166 153]
  [174 166 153]
  ...
  [110 138 155]
  [112 140 157]
  [113 141 158]]

 [[174 166 153]
  [174 166 153]
  [173 165 152]
  ...
  [112 140 157]
  [113 141 158]
  [112 140 157]]

 [[174 166 153]
  [174 166 153]
  [174 166 153]
  ...
  [109 137 154]
  [112 140 157]
  [113 141 158]]

 ...

 [[129 129 129]
  [131 130 132]
  [141 140 142]
  ...
  [147 157 167]
  [143 153 163]
  [143 153 163]]

 [[128 128 128]
  [129 129 129]
  [136 135 137]
  ...
  [135 145 155]
  [138 148 158]
  [138 148 158]]

 [[170 170 170]
  [164 164 164]
  [161 160 162]
  ...
  [128 138 148]
  [131 141 151]
  [131 141 151]]]


In [3]:
#input2=cv2.imread("nasa_3.jpg")   # nasa_3 pic since i changed from heic to jpg, the image is corrupted.(may be)

In [4]:
cv2.imshow("cinemark pic_1", input)  #first parameter is title of image and second is image variable
cv2.waitKey(1000)   #for 1000ms image will shown and then destroy
cv2.destroyAllWindows()


In [5]:
cv2.imshow("cinemark pic_2", input)  #first parameter is title of image and second is image variable
k=cv2.waitKey() 
if k==27:#until we press any key on keyboard , imag will be shown
    cv2.destroyAllWindows()
elif k==ord("d"):
    cv2.imwrite("photo_3.jpeg",input)
    cv2.destroyAllWindows()
    



In [6]:
import numpy as np
print(input.shape)    #(a,b,c)  a-height  b-width  c-no.of channels
#since it is a colour image  it has 3 channels
#height and width are in pixels

(1824, 4000, 3)


In [7]:
cv2.destroyAllWindows()

In [8]:
print("height:{0} and width:{1}".format(input.shape[0],input.shape[1]))

height:1824 and width:4000


In [9]:
cv2.imwrite("output.png",input) # we can save images in different formats


True

In [10]:
cv2.imwrite("output2.jpeg",input)

True

In [11]:
import numpy as np
np.ones((1,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.empty((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.arange(1,5,2)     #(b/w 1 to 5 in steps of 2)

array([1, 3])

In [14]:
np.linspace(1,5,4)  # 4 numbers from 1 to 5

array([1.        , 2.33333333, 3.66666667, 5.        ])